### ISSUE TITLE
Chunkwars Player Kills

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#107]
I figured we could implement player kills giving points by making killing the same player multiple times in a short amount of time against the rules and possibly add a /ch chunkwars for staff that would track who killed who in all chunkwars going on at that moment. Players would be able to see kills from their own chunkwars as they happened as well, so they could alert staff members to the rule breaking.

**Comment by Darkirby3** [comment]
Example. You start a chunkwars versus me. I kill you 1 time and than all my citizen logout. I got 1-0. I wait the end of the chunkwars and relog. I win the fight whiteout even fighting. 

That why chunkwars can't count the kill. Also you can't raid inactive city because you could score if there is no citizen online. Another problem is most of time during a chunkwars pvp ask a 3rd party pvper to help them during fight. Its not anymore finity versus fury. Who it wil make the point really hard to count because more than just 2 city get involved into the fight.

Even worst lets said we made a ally system (Who that would be extremely complicate). Like you determine who is your ally during the chunkwars. I see people at the start of a chunkwars helping a city and before the end helping the other side just because that city paid is city leader to help them instead. That would be imposible to do with a system where you determinate your ally before.

**Comment by MrSquishyDev** [comment]
"making killing the same player multiple times in a short amount of time against the rules" - so if I'm not good at pvp I'm not allowed to participate?  What if I'm the only person in my city who's online?  Of course I'm going to get killed a lot trying to defend it...the attackers could get banned for killing me?  Seriously?  Please discuss these with staff before submitting them to the tracker.  Tracker should be for ideas that have already been hashed out in chat and agreed to.
